### ISSUE TITLE
Unit-тесты?

### ISSUE THREAD

**Issue by Anoxx26** [IliaNovikov/MobileHealthNew1.0#1]
Здраствуйте Илья, а также другие разработчики MobileHealthNew1.0, я хотел узнать как сделать unit-тесты для вашего приложения?

**Comment by IliaNovikov** [comment]
Хз, выкинь компьютер

**Comment by Anoxx26** [comment]
Ты лох.

**Comment by IliaNovikov** [comment]
Сам такой.
